export interface Equipment {
  id?: number; // Optional, as it might be generated by the backend on creation
  code: string; // Ensure 'code' exists
  name: string; // Ensure 'name' exists
  nomenclature: string; // Ensure 'nomenclature' exists
  country?: number;
  group?: number;
  image?: File | string;
  model?: string;
  manufacture_name?: string;
  manufacture_address?: string;
  obsolete?: boolean | 'Yes' | 'No' | '1' | '0';
  authority?: string;
  type?: number;
  active?: boolean | '1' | '0';
  parent?: number | null;
}