export interface Manufacturer {
  id?: number; // Optional, as it might be generated by the backend on creation
  name: string;
  code: string;
  country: number; // Assuming this is an ID referencing a Country master
  address: string;
  area?: string; // Made optional as it might not always be present
  city: string;
  contact_person?: string;
  contact_number?: string;
  email?: string; // Renamed from email_id to email to match provided data
  // Add other properties if your API returns them
}